### ISSUE TITLE
Privileged containers kills user session on host

### ISSUE THREAD

**Issue by piperfw** [spurin/diveintoansible-lab#138]
I am on Arch Linux with a Wayland tiling window manager (Sway). When I run `docker-compose up`, my entire Wayland session is killed and prompts from different containers appear on my monitor, but frequently switch / glitch and aren't usable (I have to manually poweroff the machine to regain control).

This sounds exactly like the issue described here: [privileged container which is running init process inside a container kills all TTY sessions on host](https://github.com/docker/for-linux/issues/106). Based on that, thread, I am actually quite concerned what damage trying to run the lab on my system could cause.

I did however narrow it down to a minimal-breaking-example:

```
services:
  ubuntu-c:
    hostname: ubuntu-c
    container_name: ubuntu-c
    image: spurin/diveintoansible:ansible
    privileged: true

```

As suggested, it really is the `privileged` flag which appears to be destructive to my host session. Removing this, my host session isn't killed, although the container fails with an error due to lack of write access to `/tmp/`. Is there a possible work around here? Without knowing what's in the image I don't know how necessary having elevated privileges is to the labs operation. 

Note #132 is likely related.
