### ISSUE TITLE
Idea: Accessing Portal / Terminals not from localhost

### ISSUE THREAD

**Issue by dtamm** [spurin/diveintoansible-lab#16]
Hey James, great course so far, thanks for this.

Would it be possible to make the Terminals in the portal accessible even If you dont access it via localhost, e.g. from an IP? I run the docker compose in a linux vm without desktop GUI!

Regards,
Dominik

**Comment by spurin** [comment]
Hey @dtamm 

Good news, this functionality is already there, it's just not documented.  In your docker-compose.yaml file make a change to the portal section and add a line for LOCALHOST_OVERRIDE like the following with your IP/Hostname -

```
  portal:
    hostname: portal
    container_name: portal
    image: spurin/diveintoansible:portal
    environment:
     - NGINX_ENTRYPOINT_QUIET_LOGS=1
     - LOCALHOST_OVERRIDE=127.0.0.1
    depends_on:
     - centos1
     - centos2
     - centos3
     - ubuntu1
     - ubuntu2
     - ubuntu3
    ports:
     - "1000:80"
    networks:
     - diveinto.io
```

Then, ctrl-c and do another docker-compose up

You should be good to go then :-)
