### ISSUE TITLE
Cannot login ansible

### ISSUE THREAD

**Issue by CloNi** [spurin/diveintoansible-lab#17]
I get an error trying to log into ubuntu-c once I enter localhost: 1000. I use ansible / password, ansible /, Ansible / Password or ansible / pass and it keeps giving me a login error.

![image](https://user-images.githubusercontent.com/25032993/109182539-567c1a80-778d-11eb-8689-97774df8e63a.png)

**Comment by CloNi** [comment]
Solved 
![image](https://user-images.githubusercontent.com/25032993/109186839-9e04a580-7791-11eb-8ba2-718716d79da6.png)

**Comment by spurin** [comment]
Awesome @CloNi 

Glad you've got it resolved and hope you enjoy the lab and course

**Comment by spurin** [comment]
Hi @zdimitris,

In your docker-compose.yaml file, make the following edits to add LOCALHOST_OVERRIDE -

```
  portal:
    hostname: portal
    container_name: portal
    image: spurin/diveintoansible:portal
    environment:
     - NGINX_ENTRYPOINT_QUIET_LOGS=1
     - LOCALHOST_OVERRIDE=127.0.0.1
    depends_on:
     - centos1
     - centos2
     - centos3
     - ubuntu1
     - ubuntu2
     - ubuntu3
    ports:
     - "1000:80"
    networks:
     - diveinto.io
 ```
 
 Do a ctrl-c on the running environment and then do a docker-compose up, this will fix your issue 👍
