### ISSUE TITLE
Question regarding the 'extra step' for Linux users on setup...

### ISSUE THREAD

**Issue by MartynKeigher** [spurin/diveintoansible-lab#40]
Hey, 

I have the containers up and running (to a degree)... one thing I have noticed is that during the `docker-compose up` phase,  i'm not seeing the creation of the sub-folders in the ansible-lab (parent) directory. (I can confirm I have the initial lab-files (form the repo) in my home directory.

I am running my docker instance on an Ubuntu 20.04 VM, and in the read me, specifically in the 'Extra step for Linux users' section you state...

```
With the lab working and connectivity working as ansible...
```

Would you mind elaborating on this for me please? I have ran the chown command, locally (on my Ubuntu VM), but there is no 'ansible' local user there. I also swapped out the name 'ansible' for my own local username , but ... there is no '/shared/' folder to perform the action on? - I need a little more clarity on this part please?

Also.. maybe related, maybe not.. but when I try to log into ubuntu-c with ansible\password, it says the password is wrong. Is this expected?

Thanks. 
://mk

**Comment by spurin** [comment]
Hi @MartynKeigher 

We'll get this resolved.  Can you please share with me the contents of your .env file.  Also, tell me, this Ubuntu-VM that you're using, how is it running?  There will be an additional step that you will need if this is a remote system (i.e. one you access remotely via ip).

Thanks

**Comment by spurin** [comment]
To give a bit more context as you asked me to elaborate.  In the Docker Compose file, we have entries such as the following -

```
services:
  ubuntu-c:
    hostname: ubuntu-c
    container_name: ubuntu-c
    image: spurin/diveintoansible:ansible
    ports:
     - ${UBUNTUC_PORT_SSHD}:22
     - ${UBUNTUC_PORT_TTYD}:7681
    privileged: true
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/ubuntu-c/ansible:/home/ansible
     - ${ANSIBLE_HOME}/ubuntu-c/root:/root
    networks:
     - diveinto.io
```

Note how these are using the environment variables of ${CONFIG} and ${ANSIBLE_HOME}, these variables are read from the .env file.

What should happen, if it's working as expected.  When the lab environment starts, it will mount those volumes accordingly with directories on your local system.  This in turn, presents the config directory to the virtual machine as /config, this folder has details of what users etc to create.

When the container image starts up, if the /config directory exists, it reads the data in here and creates users (like the ansible user, along with a password).

If the /config mount isn't working as expected, when it starts up, it doesn't create the ansible user.

Let's take a look at the .env file and see if we can work out what is wrong.

Cheers
